version: '3.8'

services:
  nginx-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
    networks:
      ai-network:
        ipv4_address: "170.20.0.2"

networks:
  ai-network:
    external:
      name: ai-network
